spring.application.name=boardify
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# \uD65C\uC131 \uD504\uB85C\uD30C\uC77C (\uAC1C\uBC1C \uD658\uACBD \uC124\uC815)
spring.profiles.active=local

logging.level.root=error
logging.level.com.boardify=DEBUG
# SQL \uBCF4\uACE0 \uC2F6\uC73C\uBA74
logging.level.org.hibernate.SQL=DEBUG

# \uC815\uC801 \uB9AC\uC18C\uC2A4 \uB9E4\uD551 \uBE44\uD65C\uC131\uD654 (React\uAC00 \uD504\uB860\uD2B8 \uB2F4\uB2F9\uD558\uBBC0\uB85C Spring\uC774 \uC815\uC801 \uD30C\uC77C \uC11C\uBE59 \uBD88\uD544\uC694)
# /api/boards/{id} \uAC19\uC740 \uACBD\uB85C\uAC00 \uC815\uC801 \uB9AC\uC18C\uC2A4\uB85C \uC798\uBABB \uB9E4\uD551\uB418\uB294 \uBB38\uC81C \uBC29\uC9C0
spring.web.resources.add-mappings=false