spring.application.name=boardify
server.port=8081

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# \uD65C\uC131 \uD504\uB85C\uD30C\uC77C (\uAC1C\uBC1C \uD658\uACBD \uC124\uC815)
spring.profiles.active=local